# Babylon Events Console

This project provides a simple interface for running a lab environments on babylon for events where users are not expected to have authentication credentials.
The Babylon events console automatically provisions a unique lab environment to each user that connects to the console interface and provides an administrative interface for those running the lab.

## Deploying the Events Console

This project includes an OpenShift template, `deploy-template.yaml`, for configuring and deploying the babylon events console.

The following template parameters are used to configure the console:

[options="header",cols="1,2,10"]
|=======================
|Parameter |Default |Description
|NAME |"babylon-events-console" |
Name to apply to OpenShift resources (deployment, service, route, etc.).

|TEMPLATE |required |
Babylon AgnosticV catalog item template given as `<NAMESPACE>//<NAME>`.

|ACCESS_PASSWORD |none |
Optional access password if event users need to provide an access code to begin a lab.

|ADMIN_PASSWORD  |generated string |
Administrative password.
Users with this password may manage lab environments for all users.
|=======================

These are the primary parameters for using the template.
Additional parameters for advanced usage are available and documented within the template.

To deploy the Babylon events console from the command line:

--------------------------------------------------------------------------------
oc process --local -f deploy-template.yaml \
  -p NAME="babylon-events" \
  -p CATALOG_TEMPLATE_NAMESPACE="gpte" \
  -p CATALOG_TEMPLATE_NAME="tests.babylon-empty-config.dev" \
  -p ACCESS_PASSWORD="MySecret" \
  -p ADMIN_PASSWORD="AdminSecret" \
| oc create -f -
--------------------------------------------------------------------------------

Once deployed, get the route hostname for the lab console.
The same hostname should be provided to each student.

------------------------------------------------------------------------
oc get route babylon-events-console -o custom-columns=HOST:{.spec.host}
------------------------------------------------------------------------

If you deployed the console without an access password then you should keep this hostname secret until it is time for the start of the lab.
A separate lab console in a separate namespace should be used for each lab session.

## Building the Events Console

. Use the `ocp4-disconnected-lab` namespace.
+
------------------------------------------------------------
oc project ocp4-disconnected-lab
------------------------------------------------------------

. Create events console build configuration
+
------------------------------------------------------------
oc process --local -f build-template.yaml | oc apply -f -
------------------------------------------------------------

. Build events ui image
+
------------------------------------------------------------
oc start-build babylon-events-ui --from-dir=. -F
------------------------------------------------------------

. Build events operator image
+
------------------------------------------------------------
oc start-build babylon-events-operator --from-dir=. -F
------------------------------------------------------------

. Deploy events console from build image.
+
--------------------------------------------------------------------------------
OPERATOR_IMAGE=$(oc get imagestream babylon-events-operator -o jsonpath='{.status.tags[?(@.tag=="latest")].items[0].dockerImageReference}')
UI_IMAGE=$(oc get imagestream babylon-events-ui -o jsonpath='{.status.tags[?(@.tag=="latest")].items[0].dockerImageReference}')
oc process --local -f deploy-template.yaml \
  -p NAME="babylon-events" \
  -p BOOKBAG_IMAGESTREAM_NAME="bookbag" \
  -p CATALOG_TEMPLATE_NAMESPACE="gpte" \
  -p CATALOG_TEMPLATE_NAME="tests.babylon-empty-config.dev" \
  -p ADMIN_PASSWORD="r3dh4t1!" \
  -p REDIS_PASSWORD="r3d1sS3cr3t" \
  -p OPERATOR_IMAGE="${OPERATOR_IMAGE}" \
  -p UI_IMAGE="${UI_IMAGE}" \
  -p LAB_ENV_PREASSIGNMENT="true" \
  -p LAB_START_TIME="2020-04-23T00:00:00Z" \
| oc apply -f -
--------------------------------------------------------------------------------
+
NOTE: You should pass `ADMIN_PASSWORD` and `REDIS_PASSWORD` parameters if deploying repeatedly to avoid the auto-generation of values from the template defaults.
